### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by totallyhuman** [totallyhuman/doc-writer#1]
- [x] Add stuff to README
- [x] Class docstrings
- [x] Better formatting of output
- [x] File output
- [x] Line number of function or class
- [ ] Type annotations
- [ ] Indentation (to match the given script)
- [ ] Arguments with default values
- [ ] Use the tool to write docstrings for itself :3

**Comment by totallyhuman** [comment]
# ___kek___
